<a href="https://colab.research.google.com/github/officialamit558/PyTorch/blob/main/PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Pytorch fundamentals

In [ ]:
# types of learning
"""
Supervised Learning
Unsupervised Learning
Reinforcement Learning
Transfer Learning
Semi-Supervised Learning
Multi-Task Learning

"""

In [ ]:
# think about the pytorch
# what is a tensor? torch.tensor
# let's code with pytorch

In [ ]:
!nvidia-smi

Thu Mar 27 09:51:03 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   58C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


In [ ]:
print(torch.__version__)

2.6.0+cu124


In [ ]:
## Introduction is tensor in pytorch
# it way of represet the numerical data
# creating tensor
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# get tensor back as python int
scalar.item()

7

In [ ]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# matrix
matrix = torch.tensor([[7,8],
                       [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix[0][1]

tensor(8)

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
# tensor
tensor = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
tensor.ndim

3

In [ ]:
tensor.shape

torch.Size([1, 3, 3])

In [ ]:
tensor[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [ ]:
tensor[0][0]

tensor([1, 2, 3])

In [ ]:
tensor[0][0][2]

tensor(3)

In [ ]:
tensor[0][1][1]

tensor(6)

In [ ]:
# random tensors
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6147, 0.6356, 0.7510, 0.0284],
        [0.1762, 0.5145, 0.8678, 0.2182],
        [0.3267, 0.1995, 0.6091, 0.1817]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
# creating a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
# zero and ones filled tensor
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros.ndim

2

In [ ]:
zeros.shape

torch.Size([3, 4])

In [ ]:
# creating tensor of filled with one
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype , zeros.dtype

(torch.float32, torch.float32)

In [ ]:
# creating range of tensor or tensor like
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
range = torch.arange(start = 0 , end = 12 , step = 2)
range

tensor([ 0,  2,  4,  6,  8, 10])

In [ ]:
range.dtype

torch.int64

In [ ]:
range.ndim

1

In [ ]:
# creating like range like zero
like_range = torch.zeros_like(range)
like_range

tensor([0, 0, 0, 0, 0, 0])

**Note** Tensor datatypes is one of the 3 big errors you will run into with pytorch

1. Tensors not right datatypes
2. Tensors not right shape
3. Tensors not on the right device


In [ ]:
# Dealing with tensor data type

float_32 = torch.tensor([3.0,6.0,9.0],
                        dtype=None,
                        device=None, # what device is your tensor on
                        requires_grad=False)
float_32

tensor([3., 6., 9.])

In [ ]:
float_32.dtype

torch.float32

In [ ]:
 float_16_tensor = float_32.type(torch.float16)
 float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_32 * float_16_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32 = torch.tensor([3 , 6, 9] , dtype=torch.int32)
int_32

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32 * int_32

tensor([ 9., 36., 81.])

In [ ]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.1323, 0.9704, 0.5131, 0.6111],
        [0.4474, 0.0592, 0.6009, 0.0077],
        [0.1125, 0.7818, 0.3381, 0.4623]])

In [ ]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}") # check the datatype
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.1323, 0.9704, 0.5131, 0.6111],
        [0.4474, 0.0592, 0.6009, 0.0077],
        [0.1125, 0.7818, 0.3381, 0.4623]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [ ]:
# manuplating the tensor
'''
Addition
Substraction
Multiplication
Division
Matrix Multiplication

'''

In [ ]:
# creatng the tesnor
tensor = torch.tensor([1,2,3])

In [ ]:
tensor*10

tensor([10, 20, 30])

In [ ]:
tensor = tensor // 10
tensor

tensor([0, 0, 0])

In [ ]:
tensor = tensor + 10

In [ ]:
tensor = tensor - 6
tensor

tensor([4, 4, 4])

In [ ]:
# try out pytorch built in function
torch.mul(tensor , 10)

tensor([10, 20, 30])

In [ ]:
# Matrix multiplication part 1
'''
1) Element wise multiplication
2) Matrix multiplication (dot product)

'''

In [ ]:
# Element wise
tensor * tensor

tensor([1, 4, 9])

In [ ]:
# Matrix multiplication
torch.matmul(tensor , tensor)

tensor(14)

In [ ]:
tensor.ndim

1

In [ ]:
tensor.shape

torch.Size([3])

In [ ]:
# Some rule of matrix multiplication by pytorch
# One of the most common error in deep learning
# 1) The inner dimension must.
# 2) The resulting matrix has the shape of the outer dimensions.

In [ ]:
torch.matmul(torch.rand(3,2) , torch.rand(2,3))

tensor([[0.4872, 0.3814, 0.6916],
        [0.0676, 0.0478, 0.0845],
        [0.3632, 0.2969, 0.5437]])

In [ ]:
# Some more about the matrix multiplicatoins
# Shape for the matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

# torch.mm(tensor_A, tensor_B)

In [ ]:
tensor_A.shape , tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [ ]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
torch.mm(tensor_A , tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
torch.mm(tensor_A.T , tensor_B) # If the shape of the matrix is not match , than transpose the matrix

tensor([[ 76, 103],
        [100, 136]])

In [ ]:
# Tensor aggregation like min , max , mean , std , variance
x = torch.arange(0 , 100 , 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# find the mean for above data.
torch.min(x) , x.min()

(tensor(0), tensor(0))

In [ ]:
# Find the max
torch.max(x) , x.max()

(tensor(90), tensor(90))

In [ ]:
# Find the mean -> torch.mean() function requires a tensor of float32 datatype
torch.mean(x.type(torch.float32)) , x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
# find the sum from all above data in the list of x
torch.sum(x) , x.sum()

(tensor(450), tensor(450))

In [ ]:
# Find out the positions of min and max in the tensors
# We use the argmin and argmax for the maximum
x.argmin() , x.argmax()

(tensor(0), tensor(9))

In [ ]:
# Reshaping , viewing , squeezing and unsqueezing tensors
# let's creating tensor
x = torch.arange(1. , 10.)
x , x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1 , 9)
x_reshaped , x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view
z = x.view(1 , 9)
x , x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
z[:,0] = 5
z , x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on the top of each other and also do the side by side
x_stacked = torch.stack([x , x , x , x] , dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
y_stack  = torch.stack([x , x, x , x] , dim = 1)
y_stack , y_stack.shape , y_stack.ndim

(tensor([[5., 5., 5., 5.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]),
 torch.Size([9, 4]),
 2)

In [ ]:
# Squeezing , Unsqueezing and Permuting Tensors
# torch.squeeze() -> remove single dimension from target tensor.
x_squeez = x_reshaped.squeeze()

In [ ]:
x_squeez.shape , x_reshaped.shape

(torch.Size([9]), torch.Size([1, 9]))

In [ ]:
# Write code for unsqueeze the tensor to add the single dimension tensor
x_unsqueez = x_squeez.unsqueeze(dim=0)
x_unsqueez , x_unsqueez.shape , x_squeez.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([1, 9]),
 torch.Size([9]))

In [ ]:
# torch.permute -> rearrange the dimensions of a target tensor in a specidied order

x_original = torch.rand(size=(224,224,3)) # [height , width , colour_channels]

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2,0,1) # shift axis 0->1 , 1->2 , 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
# Selecting Data from tensors(indexing)
'''
Indexing with PyTorch is similar to indexing with NumPy

'''

x = torch.arange(1,10).reshape(1,3,3)
x , x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let's index our tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][2] # Middle inner

tensor([7, 8, 9])

In [ ]:
x[0][2][2] # Most inner

tensor(9)

In [ ]:
# You can also use the ":" to selelct all of a target dimension
x[: , 0]

tensor([[1, 2, 3]])

In [ ]:
x[: , : , 0]

tensor([[1, 4, 7]])

In [ ]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimesions
x[: , 1 , 1]

tensor([5])

In [ ]:
x[0 , 0 , :]

tensor([1, 2, 3])

In [ ]:
x[: , : , 2] , x[0][2][2]

(tensor([[3, 6, 9]]), tensor(9))

In [ ]:
# PyTorch tensors vs NumPy
# torch.from_numpy(ndarray) numpy to tensor
# torch.Tensor.numpy() tensor to numpy

In [ ]:
array = np.arange(1.0 , 8.0)
tensor = torch.from_numpy(array)
array , tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array = array + 1
array , tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Covert from tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor , numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
tensor = tensor + 1
tensor , numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [2]:
# Reproducbility
# start - operations - update
torch.rand(3 , 3)


tensor([[0.4838, 0.8579, 0.8747],
        [0.8001, 0.1159, 0.6603],
        [0.4589, 0.4515, 0.0349]])

In [3]:
# To reduce the randomness in neural networks and pytorch comes teh concpet of a random seed .

# create two random tensors
random_tenosr_A  = torch.rand(3,4)
randome_tensor_B = torch.rand(3 , 4)

print(random_tenosr_A)
print(randome_tensor_B)
print(random_tenosr_A == randome_tensor_B)

tensor([[0.5617, 0.1077, 0.4536, 0.7217],
        [0.8600, 0.2334, 0.3842, 0.5269],
        [0.7295, 0.0569, 0.4535, 0.4385]])
tensor([[0.5052, 0.6584, 0.8750, 0.1755],
        [0.0310, 0.0081, 0.0369, 0.6029],
        [0.3536, 0.0127, 0.6509, 0.8112]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [5]:
# Let's maek some random but reproducible tenosrs

# set the random seed
radnom_seed = 42
torch.manual_seed(radnom_seed)
random_tensor_C = torch.rand(3,4)
torch.manual_seed(radnom_seed)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [1]:
# Way of accessing the GPU
# GPU = faster computation , cuda + nvidia

# getting a gpu
!nvidia-smi

Fri Mar 28 06:44:57 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   47C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [4]:
# Check for gpu access with pytorch
torch.cuda.is_available()

True

In [4]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [5]:
# Count number of devices
torch.cuda.device_count()

1

In [6]:
# Setting up device agnostic code and putting tensors
# putting tenosr model on the gpu
tensor = torch.tensor([1,2,3])
print(tensor , tensor.device)

tensor([1, 2, 3]) cpu


In [10]:
# create a tensor
tensor = torch.tensor([1 , 2, 3, 45] , device = "cpu")
print(tensor , tensor.device)

tensor([ 1,  2,  3, 45]) cpu


In [7]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [9]:
# moving tensors back to the cpu

tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
# Exercise